<?php

namespace Tests\Unit;

use App\Helpers\DateHelper;
use PHPUnit\Framework\TestCase;

/**
 * @package Tests
 * @group unit
 * @group ready
 */
class HelpersTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testDateHelper()
    {
        $this->assertEquals(31, DateHelper::days_in_month(10, 2020));
        $this->assertNotEquals(28, DateHelper::days_in_month(2, 2020));
    }

    public function testGetDayOfWeek()
    {
        $this->assertEquals(1, DateHelper::getDayOfWeek(
            date_create('2021-08-30 09:00:00')
        ));
    }

    public function testGetWeek()
    {
        $this->assertEquals(35, DateHelper::getWeek(
            date_create('2021-08-30 09:00:00')
        ));
    }

    public  function testGetIntervalMinutes()
    {
        $this->assertEquals(510, DateHelper::getIntervalMinutes(
            date_create('2021-08-30 09:00:00'),
            date_create('2021-08-30 17:30:00')
        ));
    }
}
