<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use App\Validators;

/**
 * @package Tests
 * @group unit
 * @group ready
 */
class ValidatorsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testShiftValidator()
    {
        $this->assertTrue(Validators\ShiftValidator::ValidateShiftDates(
            date_create('2021-08-30 09:00:00'),
            date_create('2021-08-30 17:30:00')
        ));
        $this->assertFalse(Validators\ShiftValidator::ValidateShiftDates(
            date_create('2021-08-30 09:00:00'),
            date_create('2021-08-31 00:01:00')
        ));
    }
}
